### ISSUE TITLE
trying to get started

### ISSUE THREAD

**Issue by freddyh** [POPInNow/PromiseBatcher#1]
when i try to import like this
```import { PromiseBatcher } from 'PromiseBatcher';```

i get this

```SyntaxError: Unexpected token {```

i'm guessing because i dont use a build tool. so then i tried to use this
```const PromiseBatcher = require('promise-batching-queue');```

leads to this

```ReferenceError: window is not defined```

what should i do?

**Comment by popin-peter** [comment]
The minified promisebatcher.min.js seems to be requesting the `window` object.

I will look and see if I can change the webpack output to use the correct global in the backend node environment.

**Comment by popin-peter** [comment]
Hello, please try using the 0.0.2 library and importing the library like so

```
const { PromiseBatcher } = require('promise-batching-queue');
```
